name: 模組翻譯打包流程

on:
  workflow_dispatch:
    inputs:
      modpack_version:
        description: "模組包當前版本（預設為 v1.0）"
        required: false
        default: "v1.0"
      tag:
        description: "發布版本，例如 v1.0（預設為 alpha）"
        required: false
        default: "alpha"
      per_release:
        description: "預先發布版"
        type: boolean
      no_release:
        description: "停用發布，將只會產生工作流程成品，並忽略掉發布階段"
        type: boolean

jobs:
  Resourcepack-Maker:
    name: 資源包階段
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Modpack-Resourcepack.yml@main
    with:
      force_include_files: "LICENSE"
      version: ${{ github.event.inputs.tag }}

  Patch-Maker:
    name: 補丁階段
    needs: [ Resourcepack-Maker ]
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Modpack-Patch-Maker.yml@main
    with:
      modpack-version: ${{ github.event.inputs.tag }}
      modpack-patch_resourcepack_maker: ${{ needs.Resourcepack-Maker.outputs.modpack_patch_resourcepack_maker }}

  Release-It:
    name: 發布階段
    needs: [ Resourcepack-Maker, Patch-Maker ]
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Modpack-Release.yml@main
    with:
      modpack-version: ${{ github.event.inputs.tag }}
      modpack-official-version: ${{ github.event.inputs.modpack_version }}
      modpack-per-release: ${{ github.event.inputs.per_release }}
      modpack-release-ignore: ${{ github.event.inputs.no_release }}
